// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TUYGIWPm-3TmPOORGg4tRHOjt-0aECA',
    appId: '1:995965661465:web:2c332fbd70c03123bf1588',
    messagingSenderId: '995965661465',
    projectId: 'athletimate',
    authDomain: 'athletimate.firebaseapp.com',
    storageBucket: 'athletimate.appspot.com',
    measurementId: 'G-177NZHLZ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDojEPYR7lhM1S-UueM9DRX5nnrcrzEwM',
    appId: '1:995965661465:android:74788c1e35257fa0bf1588',
    messagingSenderId: '995965661465',
    projectId: 'athletimate',
    storageBucket: 'athletimate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJOcfRpjEvmGXjdgPtgZl1uyZdb4Ve0UI',
    appId: '1:995965661465:ios:b1ae541e12c9fd67bf1588',
    messagingSenderId: '995965661465',
    projectId: 'athletimate',
    storageBucket: 'athletimate.appspot.com',
    iosBundleId: 'com.example.athletimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJOcfRpjEvmGXjdgPtgZl1uyZdb4Ve0UI',
    appId: '1:995965661465:ios:b1ae541e12c9fd67bf1588',
    messagingSenderId: '995965661465',
    projectId: 'athletimate',
    storageBucket: 'athletimate.appspot.com',
    iosBundleId: 'com.example.athletimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2TUYGIWPm-3TmPOORGg4tRHOjt-0aECA',
    appId: '1:995965661465:web:da2082552d953ee3bf1588',
    messagingSenderId: '995965661465',
    projectId: 'athletimate',
    authDomain: 'athletimate.firebaseapp.com',
    storageBucket: 'athletimate.appspot.com',
    measurementId: 'G-FTVZ9FHCTX',
  );
}
